// A tiny, valid silent MP3 file encoded in base64 (approx 1 second)
const SILENT_MP3_BASE64 = 
  'SUQzAwAAAAAAFVRFTgAAAA0AAAByZWFjdC1hcHBsZXQAL/4cYQAAAAAAA0gAAAAAAA0gAAAAAAA' +
  '//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA' +
  '0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAA' +
  'AAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAA' +
  'AAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAA' +
  'A0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4' +
  'cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gA' +
  'AAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAA' +
  'AA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAA' +
  'AA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0g' +
  'AAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQ' +
  'AAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAA' +
  'AAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA' +
  '//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA0gAAAAAAA0gAAAAAAA//4cYQAAAAAAA' +
  '0gAAAAAAA0gAAAAAAA';

export function getSampleMp3(): Uint8Array {
  const binaryString = window.atob(SILENT_MP3_BASE64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}
